import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Footer, Navbar } from "@/components/shared";
import Provider from "./provider";

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={inter.className}>
            <body className="antialiased">
                <Provider>
                    <div className=" fixed top-3 inset-x-3 lg:inset-x-4 z-100 ">
                        <Navbar />
                    </div>
                    {children}
                    <Footer />
                </Provider>
            </body>
        </html>
    );
}
